# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Status-DBI
version:      v1.0.0
version_from: lib/Apache/Status/DBI.pm
installdirs:  site
requires:
    DBI:                           1.49
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
